use clap::{builder::styling::AnsiColor, builder::Styles, Parser, Subcommand};

use crate::{
    package::{PackageExecuteArgs, PackageExtractArgs, PackageInitArgs},
    recursive_package::RecursivePackageArgs,
};

const CLI_STYLE: Styles = Styles::styled()
    .header(AnsiColor::Yellow.on_default())
    .usage(AnsiColor::Green.on_default())
    .literal(AnsiColor::Green.on_default())
    .placeholder(AnsiColor::Green.on_default());

#[derive(Debug, Clone, Parser)]
#[command(name = "takopack", about = "Package Rust crates for takopack")]
#[command(version)]
#[command(styles = CLI_STYLE)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Opt,
}

#[derive(Debug, Clone, Subcommand)]
pub enum Opt {
    /// Rust/Cargo package operations
    #[command(subcommand)]
    Cargo(CargoOpt),
    /// Python package operations
    #[command(subcommand)]
    Py(PyOpt),
}

#[derive(Debug, Clone, Subcommand)]
pub enum CargoOpt {
    /// Update the crates.io index cache
    #[command(alias = "u")]
    Update,
    /// Package a single Rust crate and generate RPM spec file
    #[command(alias = "pkg")]
    Package {
        #[command(flatten)]
        init: PackageInitArgs,
        #[command(flatten)]
        extract: PackageExtractArgs,
        #[command(flatten)]
        finish: PackageExecuteArgs,
    },
    /// Recursively package a crate and all its dependencies (vendor mode)
    #[command(alias = "v")]
    Vendor {
        #[command(flatten)]
        args: RecursivePackageArgs,
    },
    /// Parse Cargo.toml dependencies and recursively generate spec files for all
    #[command(name = "parsetoml", alias = "parse")]
    ParseToml {
        /// Path to Cargo.toml file
        #[arg(value_name = "CARGO_TOML")]
        toml_path: std::path::PathBuf,

        /// Output directory for generated spec files (default: timestamped directory)
        #[arg(short, long, value_name = "DIR")]
        output: Option<std::path::PathBuf>,
    },
    /// Batch process multiple crates from a text file (one crate per line: "crate_name version")
    #[command(name = "batch")]
    Batch {
        /// Path to text file containing crate list (one per line: "name version")
        #[arg(value_name = "FILE")]
        file: std::path::PathBuf,

        /// Output directory for generated spec files (default: timestamped directory)
        #[arg(short, long, value_name = "DIR")]
        output: Option<std::path::PathBuf>,
    },
    /// Package from a local crate directory (with Cargo.toml)
    #[command(name = "localpkg", alias = "local")]
    LocalPackage {
        /// Path to directory containing Cargo.toml (or path to Cargo.toml itself)
        #[arg(value_name = "PATH")]
        path: std::path::PathBuf,

        /// Output directory for generated spec file (default: current directory)
        #[arg(short, long, value_name = "DIR")]
        output: Option<std::path::PathBuf>,

        #[command(flatten)]
        finish: PackageExecuteArgs,
    },
    /// Build a static crate capability index from RPM spec files
    #[command(name = "repo-index")]
    #[command(group(
        clap::ArgGroup::new("repo_source")
            .required(true)
            .multiple(true)
            .args(&["spec_repo_dir", "ruyispec"]),
    ))]
    RepoIndex {
        /// Directory containing generated Rust crate spec files
        #[arg(value_name = "SPEC_REPO_DIR")]
        spec_repo_dir: Option<std::path::PathBuf>,

        /// Use ruyispec.local_path from takopack.toml
        #[arg(long)]
        ruyispec: bool,

        /// Output JSON index path
        #[arg(long, value_name = "INDEX_JSON")]
        output: std::path::PathBuf,
    },
    /// Check a Cargo.toml against a static repo capability index
    #[command(name = "repo-check")]
    RepoCheck {
        /// Application Cargo.toml to check
        #[arg(value_name = "CARGO_TOML")]
        cargo_toml: std::path::PathBuf,

        /// JSON index generated by repo-index
        #[arg(long, value_name = "INDEX_JSON")]
        index: std::path::PathBuf,

        /// Recursively check selected subpackage Requires
        #[arg(long)]
        check_transitive: bool,

        /// Emit machine-readable JSON
        #[arg(long)]
        json: bool,
    },
    /// Plan add/update/conflict actions from a Cargo.toml and repo index
    #[command(name = "repo-plan")]
    RepoPlan {
        /// Application Cargo.toml to plan from
        #[arg(value_name = "CARGO_TOML")]
        cargo_toml: std::path::PathBuf,

        /// JSON index generated by repo-index
        #[arg(long, value_name = "INDEX_JSON")]
        index: std::path::PathBuf,

        /// Recursively include selected subpackage Requires in the plan
        #[arg(long)]
        check_transitive: bool,

        /// Emit machine-readable JSON
        #[arg(long)]
        json: bool,
    },
    /// Audit Rust application packages against a repo capability index
    #[command(name = "app-audit")]
    #[command(group(
        clap::ArgGroup::new("ruyispec_source")
            .required(true)
            .multiple(true)
            .args(&["ruyispec_dir", "ruyispec"]),
    ))]
    AppAudit {
        /// Local ruyispec repository directory
        #[arg(value_name = "RUYISPEC_DIR")]
        ruyispec_dir: Option<std::path::PathBuf>,

        /// Use ruyispec.local_path from takopack.toml
        #[arg(long)]
        ruyispec: bool,

        /// JSON index generated by repo-index
        #[arg(long, value_name = "INDEX_JSON")]
        index: std::path::PathBuf,

        /// Output audit report JSON path
        #[arg(long, value_name = "REPORT_JSON")]
        output: std::path::PathBuf,
    },
    /// Track dependencies from a crate and generate action list
    #[command(name = "track")]
    #[command(group(
        clap::ArgGroup::new("source")
            .required(true)
            .args(&["crate_name", "from_file"]),
    ))]
    Track {
        /// Crate name
        #[arg(value_name = "CRATE")]
        crate_name: Option<String>,

        /// Crate version (optional, uses latest if not specified)
        #[arg(value_name = "VERSION")]
        version: Option<String>,

        /// Path to Cargo.toml or Cargo.lock file
        #[arg(short = 'f', long, value_name = "FILE")]
        from_file: Option<std::path::PathBuf>,

        /// Output directory for generated specs (default: track_TIMESTAMP/)
        #[arg(short = 'o', long, value_name = "DIR")]
        output: Option<std::path::PathBuf>,

        /// Database file (default: ~/.config/takopack/crate_db.txt)
        #[arg(long, value_name = "FILE")]
        database: Option<std::path::PathBuf>,

        /// Output file for crates that need action (default: needs_action.txt)
        #[arg(long, value_name = "FILE")]
        action_file: Option<std::path::PathBuf>,
    },
}

#[derive(Debug, Clone, Subcommand)]
pub enum PyOpt {
    /// Package a Python package from PyPI and generate RPM spec file
    #[command(alias = "pkg")]
    Package {
        /// PyPI package name
        #[arg(value_name = "NAME")]
        name: String,

        /// Package version (optional, latest if omitted)
        #[arg(value_name = "VERSION")]
        version: Option<String>,

        /// Output directory for generated spec folder (default: current directory)
        #[arg(short, long, value_name = "DIR")]
        output: Option<std::path::PathBuf>,
    },
}
