use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use cargo::core::{EitherManifest, SourceId};
use cargo::util::toml::read_manifest;
use cargo::GlobalContext;
use semver::Version;

use crate::crates::all_dependencies_and_features_filtered;
use crate::takopack::control::{Description, Package};
use crate::takopack::deb_deps;
use crate::takopack::reduce_provides;

fn normalize_feature_name(feature: &str) -> String {
    feature.replace('_', "-").to_lowercase()
}

fn expand_pkgname_macro(dep: &str, pkgname: &str) -> String {
    dep.replace("%{pkgname}", pkgname)
}

fn load_lockfile_direct_dep_versions(
    cargo_toml: &Path,
    root_name: &str,
    root_version: &Version,
) -> std::collections::HashMap<String, Version> {
    let mut result = std::collections::HashMap::new();
    let Some(crate_dir) = cargo_toml.parent() else {
        return result;
    };
    let lockfile_path = crate_dir.join("Cargo.lock");
    if !lockfile_path.exists() {
        return result;
    }

    let Ok(content) = fs::read_to_string(&lockfile_path) else {
        return result;
    };
    let Ok(lockfile) = toml::de::from_str::<toml::Value>(&content) else {
        return result;
    };
    let Some(packages) = lockfile.get("package").and_then(|v| v.as_array()) else {
        return result;
    };

    let mut versions_by_name: std::collections::HashMap<String, Vec<Version>> =
        std::collections::HashMap::new();
    for pkg in packages {
        let Some(name) = pkg.get("name").and_then(|v| v.as_str()) else {
            continue;
        };
        let Some(ver_str) = pkg.get("version").and_then(|v| v.as_str()) else {
            continue;
        };
        if let Ok(ver) = Version::parse(ver_str) {
            versions_by_name
                .entry(name.to_string())
                .or_default()
                .push(ver);
        }
    }

    let root_ver = root_version.to_string();
    let root_pkg = packages.iter().find(|pkg| {
        pkg.get("name").and_then(|v| v.as_str()) == Some(root_name)
            && pkg.get("version").and_then(|v| v.as_str()) == Some(root_ver.as_str())
    });
    let Some(root_pkg) = root_pkg else {
        return result;
    };

    let Some(dep_list) = root_pkg.get("dependencies").and_then(|v| v.as_array()) else {
        return result;
    };

    for dep in dep_list {
        let Some(dep_str) = dep.as_str() else {
            continue;
        };
        let parts: Vec<&str> = dep_str.split_whitespace().collect();
        let dep_name = parts[0].to_string();
        let resolved = if parts.len() > 1 {
            Version::parse(parts[1]).ok()
        } else {
            versions_by_name.get(&dep_name).and_then(|vv| {
                if vv.len() == 1 {
                    vv.first().cloned()
                } else {
                    None
                }
            })
        };
        if let Some(ver) = resolved {
            result.insert(dep_name, ver);
        }
    }

    result
}

pub fn generate_feature_manifest(cargo_toml: &Path, output_tsv: &Path) -> Result<()> {
    let cargo_toml = cargo_toml.canonicalize().with_context(|| {
        format!(
            "failed to canonicalize Cargo.toml path: {}",
            cargo_toml.display()
        )
    })?;

    let context = GlobalContext::default()?;
    let source_id = SourceId::for_path(cargo_toml.parent().context("invalid Cargo.toml path")?)?;
    let EitherManifest::Real(manifest) = read_manifest(&cargo_toml, source_id, &context)? else {
        anyhow::bail!("manifest lacks project and package sections")
    };

    let deps_and_features = all_dependencies_and_features_filtered(&manifest, false);
    let (provides_map, reduced_features_with_deps) = reduce_provides(deps_and_features);
    let crate_name = manifest.name().as_str().replace('_', "-");
    let compat_version = crate::util::calculate_compat_version(manifest.version());
    let pkgname = format!("{}-{}", crate_name, compat_version);
    let lockfile_dep_versions = load_lockfile_direct_dep_versions(
        &cargo_toml,
        manifest.name().as_str(),
        manifest.version(),
    );

    let summary = manifest
        .metadata()
        .description
        .as_deref()
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(ToOwned::to_owned)
        .unwrap_or_else(|| format!("Rust crate \"{}\"", manifest.name()));

    if let Some(parent) = output_tsv.parent() {
        fs::create_dir_all(parent)?;
    }

    let mut out = String::new();
    out.push_str("# rustcrates-feature-manifest-v1\n");
    out.push_str("# generated by takopack cargo gen-feature-manifest\n");

    let mut features: Vec<&str> = reduced_features_with_deps.keys().copied().collect();
    features.sort_unstable();

    for feature in features {
        if feature.is_empty() {
            continue;
        }
        let feature_norm = normalize_feature_name(feature);
        out.push_str(&format!("feature\t{}\t{}\n", feature_norm, summary));

        let (f_deps, o_deps) = reduced_features_with_deps
            .get(feature)
            .cloned()
            .ok_or_else(|| anyhow::anyhow!("feature '{}' not found in reduced map", feature))?;
        let f_provides = provides_map.get(feature).cloned().unwrap_or_default();

        let mut package = Package::new(
            &pkgname,
            None,
            manifest.version(),
            Description::new(String::new(), String::new()),
            Description::new(String::new(), String::new()),
            Some(feature),
            f_deps,
            deb_deps(false, &o_deps)?,
            o_deps,
            f_provides,
            vec![],
            vec![],
            vec![],
        )?;
        package.apply_lockfile_deps(&lockfile_dep_versions);

        let mut requires = BTreeSet::new();
        for req in package.exported_requires() {
            requires.insert(expand_pkgname_macro(&req, &pkgname));
        }
        for req in requires {
            out.push_str(&format!("require\t{}\t{}\n", feature_norm, req));
        }

        let mut provides = BTreeSet::new();
        for prov in package.exported_provides() {
            provides.insert(expand_pkgname_macro(&prov, &pkgname));
        }
        for prov in provides {
            out.push_str(&format!("provide\t{}\t{}\n", feature_norm, prov));
        }
    }

    fs::write(output_tsv, out).with_context(|| {
        format!(
            "failed to write feature manifest TSV: {}",
            output_tsv.display()
        )
    })?;

    Ok(())
}
